GENERATED_HEADER = (
    "<!-- GENERATED by agent-config-sync. DO NOT EDIT HERE.\n"
    "     Edit _shared/core.md or overlays/<vendor>.md in the agent-config-sync repo,\n"
    "     then run `agent-config-sync project`. To pull a change made here back into\n"
    "     the source, run `agent-config-sync promote <runtime>`. -->\n"
)


def render(core_text: str, overlay_text: str) -> str:
    parts = [GENERATED_HEADER.rstrip("\n"), core_text.strip("\n")]
    if overlay_text.strip():
        parts.append(overlay_text.strip("\n"))
    return "\n\n".join(parts) + "\n"
